default_platform(:mac)

platform :mac do
  desc "Upload the LLB tournament app to Mac TestFlight/App Store Connect"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "8ADBXLN97S",
      issuer_id: "89f06065-abc3-4944-b620-bbf05d7f174b",
      key_filepath: "../ios/fastlane/real_ser.p8"
    )

    get_certificates(
      platform: "macos",
      api_key: api_key
    )

    get_provisioning_profile(
      platform: "macos",
      api_key: api_key,
      app_identifier: "com.ser.tan.example",
      filename: "com.ser.tan.example.macos.mobileprovision"
    )

    get_certificates(
      platform: "macos",
      type: "mac_installer_distribution",
      api_key: api_key
    )

    latest = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: "com.ser.tan.example",
      platform: "osx",
      version: "1.0.2",
      initial_build_number: 0
    )

    increment_version_number(
      version_number: "1.0.2",
      xcodeproj: "Runner.xcodeproj"
    )
    increment_build_number(
      build_number: latest + 1,
      xcodeproj: "Runner.xcodeproj"
    )

    build_mac_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates DEVELOPMENT_TEAM=W3N4W6AVQA",
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        teamID: "W3N4W6AVQA"
      }
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: "com.ser.tan.example",
      app_platform: "osx",
      apple_id: "6464065491",
      skip_waiting_for_build_processing: true
    )
  end

  desc "Upload an already exported macOS pkg"
  lane :upload_pkg do
    api_key = app_store_connect_api_key(
      key_id: "8ADBXLN97S",
      issuer_id: "89f06065-abc3-4944-b620-bbf05d7f174b",
      key_filepath: "../ios/fastlane/real_ser.p8"
    )

    upload_to_testflight(
      api_key: api_key,
      pkg: "./llb-macos-1.0.2-1.pkg",
      app_identifier: "com.ser.tan.example",
      app_platform: "osx",
      apple_id: "6464065491",
      skip_waiting_for_build_processing: true
    )
  end
end
