default_platform(:ios)

platform :ios do
  desc "Upload the LLB tournament app to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "8ADBXLN97S",
      issuer_id: "89f06065-abc3-4944-b620-bbf05d7f174b",
      key_filepath: "fastlane/real_ser.p8"
    )

    get_certificates(development: false, api_key: api_key)
    get_provisioning_profile(
      api_key: api_key,
      app_identifier: "com.ser.tan.example",
      adhoc: false,
      filename: "com.ser.tan.example.mobileprovision"
    )

    latest = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: "com.ser.tan.example",
      version: "1.0.3",
      initial_build_number: 0
    )

    increment_version_number(
      version_number: "1.0.3",
      xcodeproj: "Runner.xcodeproj"
    )
    increment_build_number(
      build_number: latest + 1,
      xcodeproj: "Runner.xcodeproj"
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates CODE_SIGN_IDENTITY=\"Apple Distribution\"",
      export_xcargs: "-allowProvisioningUpdates CODE_SIGN_IDENTITY=\"Apple Distribution\""
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: "com.ser.tan.example",
      apple_id: "6464065491",
      skip_waiting_for_build_processing: true
    )
  end

  desc "Upload App Store metadata/screenshots and submit the current build for review"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "8ADBXLN97S",
      issuer_id: "89f06065-abc3-4944-b620-bbf05d7f174b",
      key_filepath: "fastlane/real_ser.p8"
    )

    deliver(
      api_key: api_key,
      app_identifier: "com.ser.tan.example",
      app_version: "1.0.3",
      build_number: "1",
      metadata_path: "fastlane/metadata",
      screenshots_path: "fastlane/screenshots",
      skip_binary_upload: true,
      skip_metadata: false,
      skip_screenshots: false,
      overwrite_screenshots: true,
      submit_for_review: true,
      automatic_release: true,
      force: true,
      precheck_include_in_app_purchases: false,
      run_precheck_before_submit: false,
      submission_information: {
        add_id_info_uses_idfa: false,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: true,
        content_rights_contains_third_party_content: true,
        content_rights_has_rights: true
      }
    )
  end
end
